name: muOS Complete Archive Manager Theme Releases

on:
  push:
    branches: ["main"]
  workflow_dispatch:
    
concurrency: 
  group: release

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      repository-projects: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
# Create theme archives here! Zipping everything together and creating a complete theme archive.
      - name: Zip Legacy directories
        run: |
          mkdir -p /tmp/release
          for dir in current/*/; do
            [ -d "$dir" ] || continue
            zip_name=$(basename "$dir")
            zip_path="/tmp/release/${zip_name}.muxthm"
            echo "Zipping contents of $dir into $zip_path"
            
            (cd "$dir" && zip -qq -r "$zip_path" ./*)
          done
          
# Create the archive!          
      - name: List archives
        run: |
          ls -1 /tmp/release

      - name: Prepare Release
        uses: ncipollo/release-action@v1.14.0
        with:
          name: "2606.0 Andromeda Themes"
          tag: "2606.0_Andromeda_Latest"
          allowUpdates: true
          draft: true
          prerelease: false
          replacesArtifacts: true
          omitNameDuringUpdate: true
          artifacts: |
            /tmp/release/*.muxthm
            docs/theme_data.json
            docs/theme_catalogue.muxzip
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish Release
        uses: ncipollo/release-action@v1.14.0
        with:
          name: "2606.0 Andromeda Themes"
          tag: "2606.0_Andromeda_Latest"
          omitBodyDuringUpdate: true
          omitNameDuringUpdate: true
          allowUpdates: true
          draft: false
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Release Info
        id: info
        run: |
          echo "Published themes: ${{steps.date.outputs.date}} to: https://github.com/${{ steps.env.outputs.RELEASE_ORG}}/${{ steps.env.outputs.RELEASE_REPO}}"

