name: muOS Complete Archive Manager Theme Releases

on:
  push:
    branches: ["main"]
  workflow_dispatch:
    
concurrency: 
  group: release

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      repository-projects: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
# Create theme archives here! Zipping everything together and creating a complete theme archive.
      - name: Zip Legacy directories
        run: |
          mkdir -p /tmp/release
          for dir in current/*/; do
            [ -d "$dir" ] || continue
            zip_name=$(basename "$dir")
            zip_path="/tmp/release/${zip_name}.muxthm"
            echo "Zipping contents of $dir into $zip_path"
            
            (cd "$dir" && zip -qq -r "$zip_path" ./*)
          done
          
# Create the archive!          
      - name: List archives
        run: |
          ls -1 /tmp/release


      - name: Get release name for artifacts
        id: date
        run: |
            echo "date=$(date +'%Y-%m-%d_%H%M')" >> $GITHUB_OUTPUT

      - name: Push Unique and Floating Tags
        run: |
          STATIC_TAG="2606.0_Andromeda"
          UNIQUE_TAG="2606.0_Andromeda_${{ steps.date.outputs.date }}"
          
          # 1. Create and push the unique tag for history tracking
          git tag $UNIQUE_TAG
          git push origin $UNIQUE_TAG
          
          # 2. Force move the static tag locally and overwrite it on GitHub
          git tag -f $STATIC_TAG
          git push origin -f $STATIC_TAG
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Prepare Release
        uses: ncipollo/release-action@v1.14.0
        with:
          name: "2606.0 Andromeda Themes"
          tag: "2606.0_Andromeda"
          allowUpdates: true
          draft: true
          prerelease: false
          replacesArtifacts: true
          omitNameDuringUpdate: true
          artifacts: "/tmp/release/*.muxthm"
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish Release
        uses: ncipollo/release-action@v1.14.0
        with:
          name: "2606.0 Andromeda Themes"
          tag: "2606.0_Andromeda"
          omitBodyDuringUpdate: true
          omitNameDuringUpdate: true
          allowUpdates: true
          draft: false
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Release Info
        id: info
        run: |
          echo "Published themes: ${{steps.date.outputs.date}} to: https://github.com/${{ steps.env.outputs.RELEASE_ORG}}/${{ steps.env.outputs.RELEASE_REPO}}"
          
